name: pages build and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build step
        run: echo "Building..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        run: echo "Deploying..."
